# Generated by Django 5.1.15 on 2026-10-06 03:03

import django.db.models.deletion
import gestion.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compromiso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solicitante", models.CharField(max_length=160)),
                ("territorio", models.CharField(max_length=160)),
                (
                    "apoyo",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="área de apoyo"
                    ),
                ),
                ("fecha_comprometida", models.DateField()),
                (
                    "descripcion",
                    models.TextField(max_length=1000, verbose_name="descripción"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("INGRESADO", "Ingresado"),
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En proceso"),
                            ("REALIZADO", "Realizado"),
                        ],
                        default="INGRESADO",
                        editable=False,
                        max_length=10,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "actividad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compromisos",
                        to="gestion.actividad",
                        verbose_name="actividad de origen",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compromisos_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compromisos",
                        to="gestion.delegacion",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compromisos_asignados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "compromiso",
                "verbose_name_plural": "compromisos",
                "ordering": ["fecha_comprometida"],
            },
        ),
        migrations.CreateModel(
            name="CambioEstado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_anterior",
                    models.CharField(
                        choices=[
                            ("INGRESADO", "Ingresado"),
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En proceso"),
                            ("REALIZADO", "Realizado"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "estado_nuevo",
                    models.CharField(
                        choices=[
                            ("INGRESADO", "Ingresado"),
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En proceso"),
                            ("REALIZADO", "Realizado"),
                        ],
                        max_length=10,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "observacion",
                    models.TextField(max_length=500, verbose_name="observación"),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compromiso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historial",
                        to="gestion.compromiso",
                    ),
                ),
            ],
            options={
                "verbose_name": "cambio de estado",
                "verbose_name_plural": "cambios de estado",
                "ordering": ["fecha"],
            },
        ),
        migrations.CreateModel(
            name="Evidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                ("archivo", models.FileField(upload_to=gestion.models.ruta_evidencia)),
                ("subida_en", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de revisión"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "Rechazada"),
                            ("CORRECCION", "Corrección solicitada"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                    ),
                ),
                ("revisada_en", models.DateTimeField(blank=True, null=True)),
                (
                    "observacion",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="observación"
                    ),
                ),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidencias",
                        to="gestion.actividad",
                    ),
                ),
                (
                    "subida_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidencias_subidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verificador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidencias_revisadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "evidencia",
                "verbose_name_plural": "evidencias",
                "ordering": ["-subida_en"],
            },
        ),
    ]
