# Generated by Django 5.2.17 on 2026-10-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0002_sprint_evidencias_compromisos"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("usuario", models.CharField(max_length=150)),
                ("accion", models.CharField(db_index=True, max_length=30)),
                ("entidad", models.CharField(blank=True, max_length=60)),
                ("identificador", models.CharField(blank=True, max_length=40)),
                ("detalle", models.CharField(blank=True, max_length=300)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "registro de auditoría",
                "verbose_name_plural": "bitácora de auditoría",
                "ordering": ["-fecha"],
            },
        ),
    ]
